before_install:
- openssl aes-256-cbc -K $encrypted_10e7321a306e_key -iv $encrypted_10e7321a306e_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project url-shortener-back


script:
# [START deploy]
# Deploy the app
- gcloud -q app deploy app.yaml --promote
